name: Create Archive

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 1. Grant write permissions to the GITHUB_TOKEN
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Remove old archive if it exists
      run: |
        rm -f LimaruResourcePack.zip

    - name: Zip release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'LimaruResourcePack.zip'
        exclusions: '*.git* *.github* /*node_modules/* .editorconfig CODE_OF_CONDUCT.md CONTRIBUTING.md README.md'

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Check if there are any changes to commit (i.e. the zip file was updated/created)
        git add LimaruResourcePack.zip
        if git diff --staged --quiet; then
          echo "No changes to the zip file."
        else
          git commit -m "auto: update LimaruResourcePack.zip [skip ci]"
          git push origin master
        fi
